version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "Europe/Amsterdam"
      WEBPASSWORD: "your-secure-password"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"    # Pi-hole web UI mapped to port 8080
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped

  casaos:
    container_name: casaos
    image: icewhale/casaos:latest
    ports:
      - "3000:3000"  # CasaOS UI
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
