name: Deploy Pi-hole

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Raspberry Pi via Tailscale SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tailscale & join tailnet
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up \
            --authkey $TAILSCALE_AUTHKEY \
            --hostname gha-runner \
            --accept-dns=false

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy Pi-hole
        run: |
          ssh \
            -o "ProxyCommand tailscale ssh-proxy %h" \
            -i ~/.ssh/id_rsa \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/pi-devops-lab/docker/pi-hole
            cat > .env <<EOT
            PIHOLE_IMAGE=pihole/pihole:latest
            PLATFORM=linux/arm64
            TZ=Europe/Amsterdam
            WEBPASSWORD=${{ secrets.PIHOLE_WEBPASSWORD }}
            EOT

            docker compose pull
            docker compose down
            docker compose up -d
          EOF
