name: Deploy Pi-hole

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Raspberry Pi via Tailscale SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tailscale & join tailnet with SSH enabled
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up \
            --authkey $TAILSCALE_AUTHKEY \
            --hostname gha-runner \
            --advertise-tags=tag:ci-runner \
            --accept-dns=false \
            --ssh

      - name: Verify Tailscale connection
        run: |
          echo "=== Tailscale status ==="
          tailscale status
          echo "=== Pinging Pi (tag:pi) ==="
          tailscale ping -c 3 tag:pi

      - name: Deploy Pi-hole via Tailscale SSH
        run: |
          sudo tailscale ssh pi@tag:pi << 'EOF'
          cd ~/pi-devops-lab/docker/pi-hole
          cat > .env <<EOT
          PIHOLE_IMAGE=pihole/pihole:latest
          PLATFORM=linux/arm64
          TZ=Europe/Amsterdam
          WEBPASSWORD=${{ secrets.PIHOLE_WEBPASSWORD }}
          EOT

          docker compose pull
          docker compose down
          docker compose up -d
          EOF
